# Numpy

## 1. Numpy arrays

fl_sp bevat de oppervlaktes in vierkante meters van 5 winkels.   
turnover bevat de omzet in Britse Ponden (GBP) van dezelfde 5 winkels (in dezelfde volgorde).

- Importeer Numpy.
- Zet de lists om in de Numpy arrays np_fl en np_to.
- Print de types van de arrays.
- Maak een nieuwe array to_eur aan waarin de omzetten worden omgezet in Euro bedragen. 
    - Zoek de wisselkoers op op het Internet.  
- Print to_eur.
- Bereken de EUR omzet per vierkante meter per winkel in de nieuwe array to_sqm.
- Print de eerste 3 regels van to_sqm
- Als de omzet per vierkante meter hoger is dan 230 dan wordt dit als 'goed' gezien. Print de elementen die hoger zijn dan deze grenswaarde.
- Print de hoogste omzet per vierkante meter.

In [2]:
fl_sp = [18526, 18569, 12288, 17092, 11307]
turnover = [3410865, 4034051, 2297810, 2398990, 2288235]

#Import:
import numpy as np

#Convert to arrays
np_fl = np.array(fl_sp)
np_to = np.array(turnover)

#Print types
print(type(np_fl), type(np_to))

#Convert to EUR and print
to_eur = np_to * 1.14
print(np.around(to_eur, 2))

#Calculate EUR turnover per sqm and print first 3 items
to_sqm = to_eur / fl_sp
print(np.around(to_sqm[:3], 2))

#Print to per sqm > 230
goed = to_sqm > 230 
print(np.around(to_sqm[goed], 2))

#Print the highest turnover
print(np.around(np.max(to_sqm), 2))


<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[3888386.1  4598818.14 2619503.4  2734848.6  2608587.9 ]
[209.89 247.66 213.18]
[247.66 230.71]
247.66


## 2 Numpy 2D arrays
De list met lists fl_sp_to bevat de oppervlaktes in vierkante meters en de omzetten in GBP van 5 winkels.
- Zet fl_sp_to om in een 2D Numpy array.
- Laat zien hoeveel rijen en kolommen fl_sp bevat.
- Print de tweede kolom van de laatste 4 regels.
- Print de tweede rij tot en met de vierde rij.
- Converteer de vloeroppervlaktes naar feet (i.p.v. vierkante meters) en de GBP bedragen naar EUR. Zoek de juiste omrekenfactoren op op het internet. De nieuwe array krijgt als naam conv.
- Print conv.
- Elke winkelmanager krijgt een bonus. De bonus percentages staan in de bonus list. Het bonusbedrag is het  bonuspercentage maal de omzet. Maak de array bon_amount met daarin de vloeroppervlaktes en de bonus bedragen. Zet hiervoor eerst de bonus list om in een array. Gebruik deze array bij het maken van bon_amount.
- Print bon_amount.

In [4]:
fl_sp_to = [[18526, 3410865],
            [18569, 4034051],
            [12288, 2297810], 
            [17092, 2398990], 
            [11307, 2288235]]

#Convert into a 2D array
fl_sp_to_arr = np.array(fl_sp_to)

#print shape
print(np.shape(fl_sp_to_arr))

#print second column of last 4 rows
print(fl_sp_to_arr[-4:, 1:])

#print second row up to and including the 4th row
print(fl_sp_to_arr[1:4])

#Convert to feet and EUR
conv = np.around(fl_sp_to_arr * [[10.76391042, 1.14]], 2)
print(conv)

#Bonus table
bonus = [[1, 0.010],
         [1, 0.008],
         [1, 0.007], 
         [1, 0.011], 
         [1, 0.005]]

# bonus amount
bon_arr = np.array(bonus)
bon_amount = fl_sp_to_arr * bon_arr
print(bon_amount)


(5, 2)
[[4034051]
 [2297810]
 [2398990]
 [2288235]]
[[  18569 4034051]
 [  12288 2297810]
 [  17092 2398990]]
[[ 199412.2  3888386.1 ]
 [ 199875.05 4598818.14]
 [ 132266.93 2619503.4 ]
 [ 183976.76 2734848.6 ]
 [ 121707.54 2608587.9 ]]
[[18526.    34108.65 ]
 [18569.    32272.408]
 [12288.    16084.67 ]
 [17092.    26388.89 ]
 [11307.    11441.175]]


## 3 Integratie opdracht

In onderstaande cel worden winkelgegevens geimporteerd uit een csv-bestand met behulp van Pandas. Dit is iets waar we de komende lessen veel dieper op in gaan. Het resultaat is dat er een 2D numpy array st_to beschikbaar is voor deze opdracht.

In st_to vind je het aantal medewerkers (staff members) en de omzet (turnover) per winkel. We verwachten dat er een verband is tussen het aantal medewerkers en de omzet. Dat gaan we nu onderzoeken.

- Bereken het gemiddelde, de mediaan en de standaarddeviatie van beide kolommen.
- Wat valt je op aan deze waardes?
- Print de array. Zijn er waardes die sterk afwijken? Welke zijn dat?
- Print de regels uit st_to die hetzelfde aantal medewerkers hebben als het mediane aantal medewerkers.
- Print de correlatiecoefficient voor beide kolommen.
- Welke opties zijn er om de datakwaliteit te verhogen?

In [8]:
#Don't remove this:
import pandas as pd
import numpy as np
storedata = pd.read_csv('storedata.csv', encoding = "ISO-8859-1")
st_to = storedata[['Staff', 'Profit']].values

# Start coding here:
# Staff
print(np.mean(st_to[:, 0]))
print(np.median(st_to[:, 0]))
print(np.std(st_to[:, 0]))

# Turnover
print(np.around(np.mean(st_to[:, 1]), 2))
print(np.median(st_to[:, 1]))
print(np.around(np.std(st_to[:, 1]), 2))

# Staff median and mean are not close and a high stdev. The data needs further investigation. First step: print the array
print(st_to)  # afwijkingen staff = [-2, 300, 600] , turnover = [turnover < 1 mil]


# print the lines that have a staff number that is the same as the median:
to_print = st_to[:, 0] == np.median(st_to[:, 0])
print(f"\n\n{st_to[to_print]}")

print(np.corrcoef(st_to[:, 0], st_to[:,1]))





13.352941176470589
7.0
56.38399457550571
2990980.95
3018400.5
713958.0
[[      9 3410865]
 [      8 4034051]
 [     -2 2297810]
 [      7 2398990]
 [      7 2288235]
 [      7 3058134]
 [      8 2793160]
 [      9 3345936]
 [      9 3117205]
 [      7 3153278]
 [      9 3056804]
 [      8 1801619]
 [      8 3797953]
 [      8 3138911]
 [      5 2724068]
 [      6 2382751]
 [      8 3321899]
 [      6 2803867]
 [      9 3640627]
 [      9 3075352]
 [      6 3491993]
 [      7 3252148]
 [      7 3041618]
 [      6 3737466]
 [      9 4217291]
 [      5 2008363]
 [      7 3516397]
 [      6 3957233]
 [      5 2942839]
 [      9 2242288]
 [      6 2616387]
 [      7 2493975]
 [      6 2203994]
 [      8 2458785]
 [      8 4253984]
 [      9 4185306]
 [      9 4160531]
 [      7 3100521]
 [      6 3246954]
 [      5 2085733]
 [      9 3741911]
 [      9 2506748]
 [      7 2393869]
 [      8 4137224]
 [      9 3572475]
 [      9 3121837]
 [      5 2799074]
 [      5 2707402]
 [      5 4176642

TypeError: type() takes 1 or 3 arguments

In [15]:
test = np.logical_and(st_to[:, 0] > 0, st_to[:,0] < 300)
display(test)
new_array = st_to[test]
np.corrcoef(new_array[:,0], new_array[:,1])

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

array([[1.        , 0.29000514],
       [0.29000514, 1.        ]])